---

- name: extensions > Checks already enabled extensions
  shell: "dpkg --get-selections 'php{{ (elao_php_version == 5)|ternary(5, '') }}-*'|grep -v deinstall|cut -f 1"
  register: _elao_php_extensions_enabled_output
  always_run: yes
  ignore_errors: true
  changed_when: false

- name: extensions > Compute already enabled extensions
  set_fact:
    _elao_php_extensions_enabled: "{{ _elao_php_extensions_enabled_output.stdout_lines|difference(elao_php_extensions_exclude)|list }}"

- name: extensions > Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: elao_php_extensions|map('regex_replace','^(.*)$','php' ~ (elao_php_version == 5)|ternary(5, '') ~ '-\\1')|difference(_elao_php_extensions_enabled)
  notify:
    - php fpm restart

- name: extensions > Remove packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: _elao_php_extensions_enabled|difference(elao_php_extensions|map('regex_replace','^(.*)$','php' ~ (elao_php_version == 5)|ternary(5, '') ~ '-\\1')|list)
  notify:
    - php fpm restart
