---

- name: php fpm restart
  command: "php{{ (elao_php_version == 5)|ternary(5, '') }}-fpm{{ (elao_php_version == 5)|ternary('', elao_php_version) }} -t"
  when: "'fpm' in elao_php_sapis"
  changed_when: true
  notify:
    - do php fpm restart

- name: do php fpm restart
  service:
    name:  "php{{ elao_php_version }}-fpm"
    state: restarted
  when: "'fpm' in elao_php_sapis"

- name: php cli restart
  debug:
    msg: "skip php-cli restart"
